Pages/Events/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using KampongTalk.Models;
using KampongTalk.Pages.Search;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mighty;

namespace KampongTalk.Pages.Events
{
    public class CreateModel : PageModel
    {
        [BindProperty] public Event myEvent { get; set; } = new Event();

        private User CurrentUser { get; set; }
        public dynamic LangData { get; set; }

        public string timeErrMsg { get; set; }

        public MightyOrm eventDb { get; set; } =
            new MightyOrm(ConfigurationManager.AppSetting["ConnectionStrings:KampongTalkDbConnection"], "Events");

        // public IEnumerable<SelectListItem> ListOfTimeIntervals = TimeEnum.getListOfTimeIntervals();
        public IEnumerable<SelectListItem> ListOfStartTimeIntervals { get; set; } = TimeEnum.getListOfTimeIntervals();
        public IEnumerable<SelectListItem> ListOfEndTimeIntervals { get; set; } = GetEndTimeEnum("06:00 AM");

        public IActionResult OnGet()
        {
            // Get current user
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            if (CurrentUser == null) return Redirect("/Accounts/Login");
            LangData = UserPrefApi.GetLangByUid(CurrentUser); // <- Param should be the user object, not Uid.

            return Page();
        }

        public static IEnumerable<SelectListItem> GetEndTimeEnum(string startTime)
        {
            return TimeEnum.getListOfTimeIntervalsAfter(startTime);
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
                var startDateTime = DateTime.ParseExact(myEvent.StartTime, "hh:mm tt", CultureInfo.InvariantCulture);
                var endDateTime = DateTime.ParseExact(myEvent.EndTime, "hh:mm tt", CultureInfo.InvariantCulture);
                if (endDateTime > startDateTime)
                {
                    var startTimeSpan = startDateTime.TimeOfDay;
                    var endTimeSpan = endDateTime.TimeOfDay;

                    // TO render the correct DateTime & save in DB (Take the end time as the timing)
                    var dtDate = Convert.ToDateTime(myEvent.Date);
                    var renderedDate = dtDate.ToString("yyyy-MM-dd");
                    var dt = Convert.ToDateTime(renderedDate + " " + myEvent.EndTime);

                    myEvent.Date = dt;
                    myEvent.CreatorId = CurrentUser.Uid;
                    myEvent.Attendees = $"{myEvent.CreatorId};";
                    myEvent.Duration = Convert.ToString(endTimeSpan.TotalHours - startTimeSpan.TotalHours);
                    SearchApi.PutKeyword(myEvent.Name, 5, myEvent.Eid);
                    SearchApi.PutRelevancy(myEvent.Description, myEvent.Eid);
                    eventDb.Insert(myEvent);
                    return Redirect("/Events/MyEvents");
                }

                timeErrMsg = "End Time must be later than Start time";
                return Page();
            }

            return Page();
        }
    }
}

Pages/Events/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using KampongTalk.Models;
using KampongTalk.Pages.Search;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mighty;

namespace KampongTalk.Pages.Events
{
    public class EditModel : PageModel
    {
        [BindProperty] public Event myEvent { get; set; }

        public dynamic savedEvent { get; set; }

        [BindProperty] public double Eid { get; set; }

        public dynamic LangData { get; set; }

        public string eventDate { get; set; }

        public string timeErrMsg { get; set; }

        public MightyOrm eventDb { get; set; } =
            new MightyOrm(ConfigurationManager.AppSetting["ConnectionStrings:KampongTalkDbConnection"], "Events",
                "Eid");

        private User CurrentUser { get; set; }

        // public IEnumerable<SelectListItem> ListOfTimeIntervals = TimeEnum.getListOfTimeIntervals();
        public IEnumerable<SelectListItem> ListOfStartTimeIntervals { get; set; } = TimeEnum.getListOfTimeIntervals();
        public IEnumerable<SelectListItem> ListOfEndTimeIntervals { get; set; } = GetEndTimeEnum("06:00 AM");

        public static IEnumerable<SelectListItem> GetEndTimeEnum(string startTime)
        {
            return TimeEnum.getListOfTimeIntervalsAfter(startTime);
        }

        public IActionResult OnGet(string eid)
        {
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            if (CurrentUser == null) return Redirect("/Accounts/Login");

            LangData = UserPrefApi.GetLangByUid(CurrentUser); 

            Eid = Convert.ToInt64(eid);
            savedEvent = eventDb.Single($"Eid = {Eid}");

            if (savedEvent.CreatorId == CurrentUser.Uid)
            {
                // Don't allow users to edit events that are already over
                if (DateTime.Now >= savedEvent.Date) return Redirect($"/Events/View/{eid}");

                DateTime dt = Convert.ToDateTime(savedEvent.Date);
                eventDate = dt.ToString("yyyy-MM-dd");
                return Page();
            }

            return Redirect($"/Events/View/{eid}");
        }

        public IActionResult OnPost()
        {
            // Ensure user is authorized to edit
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            if (CurrentUser == null) return Redirect("/Accounts/Login");
            Eid = Convert.ToInt64(Eid);
            savedEvent = eventDb.Single($"Eid = {Eid}");
            if (savedEvent.CreatorId != CurrentUser.Uid) return Redirect("/Accounts/Login");

            if (ModelState.IsValid)
            {
                var startDateTime = DateTime.ParseExact(myEvent.StartTime, "hh:mm tt", CultureInfo.InvariantCulture);
                var endDateTime = DateTime.ParseExact(myEvent.EndTime, "hh:mm tt", CultureInfo.InvariantCulture);
                var startTimeSpan = startDateTime.TimeOfDay;
                var endTimeSpan = endDateTime.TimeOfDay;
                if (endDateTime > startDateTime)
                {
                    savedEvent = eventDb.Single($"Eid = {Eid}");
                    savedEvent.Name = myEvent.Name;
                    savedEvent.Location = myEvent.Location;
                    savedEvent.StartTime = myEvent.StartTime;
                    savedEvent.EndTime = myEvent.EndTime;
                    savedEvent.Description = myEvent.Description;

                    // TO render the correct DateTime & save in DB (Take the end time as the timing)
                    var dtDate = Convert.ToDateTime(myEvent.Date);
                    var renderedDate = dtDate.ToString("yyyy-MM-dd");
                    var dt = Convert.ToDateTime(renderedDate + " " + myEvent.EndTime);
                    savedEvent.Date = dt;
                    savedEvent.Duration = Convert.ToString(endTimeSpan.TotalHours - startTimeSpan.TotalHours);
                    
                    SearchApi.PutKeyword(savedEvent.Name, 5, savedEvent.Eid);
                    SearchApi.PutRelevancy(savedEvent.Description, savedEvent.Eid);
                    eventDb.Update(savedEvent);
                    return Redirect($"/Events/View/{savedEvent.Eid}");
                }
                else
                {
                    timeErrMsg = "End Time must be later than Start time";
                    savedEvent = eventDb.Single($"Eid = {Eid}");
                    DateTime dt = Convert.ToDateTime(savedEvent.Date);
                    eventDate = dt.ToString("yyyy-MM-dd");
                    return Page();
                }
            }

            return Page();
        }
    }
}

Pages/Events/Index.cshtml.cs
using System;
using System.Collections.Generic;
using KampongTalk.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mighty;

namespace KampongTalk.Pages.Events
{
    public class IndexModel : PageModel
    {
        public static DateTime nowDt = DateTime.Now;
        public static string nowDtString = nowDt.ToString("yyyy-MM-dd HH:mm:ss");

        public static MightyOrm eventDb { get; set; } =
            new MightyOrm(ConfigurationManager.AppSetting["ConnectionStrings:KampongTalkDbConnection"], "Events");

        public IEnumerable<dynamic> allEvents { get; set; } = eventDb.All($"Date > '{nowDtString}'");

        private User CurrentUser { get; set; }
        public dynamic LangData { get; set; }
        
        public void OnGet()
        {
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            LangData = UserPrefApi.GetLangByUid(CurrentUser);
        }
    }
}

Pages/Events/MyEvents.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mighty;

namespace KampongTalk.Pages.Events
{
    public class MyEventsModel : PageModel
    {
        public static long userId { get; set; } = 7;
        public static MightyOrm eventDb { get; set; } = new MightyOrm(ConfigurationManager.AppSetting["ConnectionStrings:KampongTalkDbConnection"], "Events");
        
        public IEnumerable<dynamic> myCreatedEvents { get; set; } = eventDb.All($"CreatorId = {userId}");
        public IEnumerable<dynamic> mySignedUpEvents { get; set; } = eventDb.All();
        public IEnumerable<dynamic> myPastEvents { get; set; } = eventDb.All();

        public void OnGet()
        {

        }
    }
}

Pages/Events/MyEvents/Index.cshtml.cs
using System;
using System.Collections.Generic;
using KampongTalk.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mighty;

namespace KampongTalk.Pages.Events.MyEvents
{
    public class IndexModel : PageModel
    {
        public static DateTime nowDt = DateTime.Now;
        public static string nowDtString = nowDt.ToString("yyyy-MM-dd HH:mm:ss");

        public long userId { get; set; }
        public dynamic LangData { get; set; }

        public static MightyOrm eventDb { get; set; } =
            new MightyOrm(ConfigurationManager.AppSetting["ConnectionStrings:KampongTalkDbConnection"], "Events");

        public IEnumerable<dynamic> myUpcomingEvents { get; set; }


        private User CurrentUser { get; set; }

        public IActionResult OnGet()
        {
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            if (CurrentUser == null) return Redirect("/Accounts/Login");
            LangData = UserPrefApi.GetLangByUid(CurrentUser);

            userId = CurrentUser.Uid;
            myUpcomingEvents = eventDb.All($"Attendees like '%{CurrentUser.Uid}%' AND Date > '{nowDtString}'");
            return Page();
        }
    }
}

Pages/Events/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using IdGen;
using KampongTalk.Models;
using KampongTalk.Tools;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mighty;

namespace KampongTalk.Pages.Events
{
    public class ViewModel : PageModel
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IEventRecommender _recommender;

        public ViewModel(IWebHostEnvironment environment, IEventRecommender recommender)
        {
            _environment = environment;
            _recommender = recommender;
        }

        [BindProperty] public long Eid { get; set; }

        private User CurrentUser { get; set; }

        public dynamic OwnerUser { get; set; }

        public static MightyOrm eventDb { get; set; } =
            new MightyOrm(ConfigurationManager.AppSetting["ConnectionStrings:KampongTalkDbConnection"], "Events",
                "Eid");

        public static MightyOrm userDb { get; set; } =
            new MightyOrm(ConfigurationManager.AppSetting["ConnectionStrings:KampongTalkDbConnection"], "Users",
                "Uid");

        public dynamic myEvent { get; set; }
        public string eventDate { get; set; }

        // IS the current user the owner of the listing
        public bool amOwner { get; set; }

        // Has the current user added the listing to their list
        public bool hasAdded { get; set; }

        // Has the event ended?
        public bool isOver { get; set; }

        public IEnumerable<long> recommendedIds { get; set; }

        public List<dynamic> recommendedEvents { get; set; } = new List<dynamic>();

        [BindProperty] public IFormFile eventImage { get; set; }
        public dynamic LangData { get; set; }

        public async Task OnGet(string eid)
        {
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            LangData = UserPrefApi.GetLangByUid(CurrentUser);
            // TO retrieve the savedEvent object from db
            Eid = Convert.ToInt64(eid);
            myEvent = eventDb.Single($"Eid = {Eid}");
            OwnerUser = userDb.Single($"Uid = {myEvent.CreatorId}");

            var eventDateTime = Convert.ToDateTime(myEvent.Date);
            eventDate = eventDateTime.ToLongDateString();

            recommendedIds = await _recommender.Recommend($"{myEvent.Name} {myEvent.Description}");

            var stopAtThreeCounter = 0;
            foreach (var recommendedId in recommendedIds)
            {
                // We only want the top 3 recommendations
                if (stopAtThreeCounter > 2)
                    break;

                // We don't want to recommend the same item
                if (recommendedId == myEvent.Eid)
                    continue;

                var recommendedEvent = eventDb.Single($"Eid = {recommendedId}");
                recommendedEvents.Add(recommendedEvent);
                stopAtThreeCounter += 1;
            }

            if (DateTime.Now >= myEvent.Date) isOver = true;

            if (CurrentUser != null)
            {
                if (myEvent.Attendees.Contains(CurrentUser.Uid.ToString())) hasAdded = true;
                if (myEvent.CreatorId == CurrentUser.Uid) amOwner = true;
            }
        }


        public IActionResult OnPost(IFormFile eventImage)
        {
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            var savedEvent = eventDb.Single($"Eid = {Eid}");
            if (savedEvent.CreatorId == CurrentUser.Uid)
            {
                var imgExt = eventImage.FileName.Split('.').Last();
                var genImgNum = new IdGenerator(2).CreateId();
                var genImgName = genImgNum + "." + imgExt;
                var file = Path.Combine(_environment.ContentRootPath, "wwwroot/imgs/Events", genImgName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    eventImage.CopyTo(fileStream);
                }

                // if current image is not default.jpg, we will delete on our end
                if (savedEvent.Img != "default.jpg")
                {
                    var currentImgPath = Path.Combine(_environment.ContentRootPath, "wwwroot/imgs/Events", savedEvent.Img);
                    System.IO.File.Delete(currentImgPath);
                }

                savedEvent.Img = genImgName;
                eventDb.Update(savedEvent);
                return Redirect($"/Events/View/{Eid}");
            }

            return Page();
        }

        public IActionResult OnPostAddOrRemove()
        {
            CurrentUser = new User().FromJson(HttpContext.Session.GetString("CurrentUser"));
            Eid = Convert.ToInt64(Eid);
            myEvent = eventDb.Single($"Eid = {Eid}");

            if (CurrentUser != null)
            {
                // Don't allow creator to remove his own listing
                if (myEvent.CreatorId != CurrentUser.Uid)
                {
                    var currentUid = CurrentUser.Uid.ToString();
                    // If user has already added the event, we will remove it
                    if (myEvent.Attendees.Contains(currentUid))
                        myEvent.Attendees = myEvent.Attendees.Replace($"{currentUid};", "");
                    // If user hasn't added the event, we will add it
                    else
                        myEvent.Attendees = myEvent.Attendees + $"{currentUid};";
                    eventDb.Update(myEvent);
                }

                return Redirect($"/Events/View/{Eid}");
            }

            return Redirect("/Accounts/Login");
        }
    }
}

Pages/Events/Create.cshtml
@page
@model KampongTalk.Pages.Events.CreateModel

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <link rel="stylesheet" href="~/css/eventForm.css">

    <script>
    SetMinDate = () => {
        var now = new Date();

        var day = ("0" + now.getDate()).slice(-2);
        var month = ("0" + (now.getMonth() + 1)).slice(-2);

        var today = now.getFullYear() + "-" + (month) + "-" + (day);

        $('#eventDate').val(today);
        $('#eventDate').attr('min', today);
    }

    SetMinDate()
    console.log("DONE!")
</script>

}

<section class="section">
    <div class="container">
        <h1 class="title">@Model.LangData.events.index.create</h1>
        <form method="post">
            <div class="field">
                <label class="label">@Model.LangData.events.create.Name</label>
                <div class="control">
                    <input class="input form-input-50" type="text" asp-for="myEvent.Name">
                </div>
            </div>

            <div class="field">
                <label class="label">@Model.LangData.events.create.Description</label>
                <div class="control form-input-50">
                    <textarea id="eventDesc" class="textarea" asp-for="myEvent.Description"></textarea>
                </div>
            </div>

            <div class="field">
                <label class="label">@Model.LangData.events.create.Date</label>
                <div class="control">
                    <input class="input form-input-50" id="eventDate" type="date" id="eventDate" asp-for="myEvent.Date"/>
                </div>
            </div>

            <div class="field is-grouped">
                <div class="control">
                    <label class="label">@Model.LangData.events.create.Start</label>
                    <div class="control">
                        <div class="select">
                            <select id="startTime" asp-for="myEvent.StartTime" asp-items="Model.ListOfStartTimeIntervals" class="form-control"></select>
                        </div>
                    </div>
                </div>

                <div class="control">
                    <label class="label">@Model.LangData.events.create.End</label>
                    <div class="control">
                        <div class="select">
                            <select id="endTime" asp-for="myEvent.EndTime" asp-items="Model.ListOfEndTimeIntervals" class="form-control"></select>
                        </div>
                    </div>
                    <p class="help is-danger">@Model.timeErrMsg</p>
                </div>
            </div>


            <div class="field">
                <label class="label">@Model.LangData.events.create.Location</label>
                <div class="control">
                    <input class="input form-input-50" asp-for="myEvent.Location"></input>
                    <br/>
                    <a class="has-text-success" href="https://www.skype.com/en/free-conference-call/" target="_blank">@Model.LangData.events.create.MeetingLink</a>
                </div>
            </div>

            <div class="field">
                <div class="control buttons">
                    <button class="button is-light" onclick="location.href='/Events';">@Model.LangData.cancel</button>
                    <button class="button is-warning is-light">@Model.LangData.events.create.Create</button>
                </div>
            </div>

        </form>
    </div>
</section>

Pages/Events/Edit.cshtml
@page "{eid}"
@model KampongTalk.Pages.Events.EditModel

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <link rel="stylesheet" href="~/css/eventForm.css">

    <script>
    SetMinDate = () => {
        var now = new Date();

        var day = ("0" + now.getDate()).slice(-2);
        var month = ("0" + (now.getMonth() + 1)).slice(-2);

        var today = now.getFullYear() + "-" + (month) + "-" + (day);

        $('#eventDate').attr('min', today);
    }

    SetMinDate()

    $('#eventDate').val('@Model.eventDate');
    $('#startTime').val('@Model.savedEvent.StartTime');
    $('#endTime').val('@Model.savedEvent.EndTime');
    $('#eventDesc').val('@Model.savedEvent.Description');

    console.log("DONE!")
</script>

}

<div class="container">
    <form method="post">
        <div class="field">
            <label class="label">@Model.LangData.events.create.Name</label>
            <div class="control">
                <input class="input form-input-50" type="text" value="@Model.savedEvent.Name" asp-for="myEvent.Name">
            </div>
        </div>

        <div class="field">
            <label class="label">@Model.LangData.events.create.Description</label>
            <div class="control form-input-50">
                <textarea id="eventDesc" class="textarea" asp-for="myEvent.Description"></textarea>
            </div>
        </div>

        <div class="field">
            <label class="label">@Model.LangData.events.create.Date</label>
            <div class="control">
                <input class="input form-input-50" id="eventDate" type="date" value="@Model.eventDate" id="eventDate" asp-for="myEvent.Date"/>
            </div>
        </div>

        <div class="field is-grouped">
            <div class="control">
                <label class="label">@Model.LangData.events.create.Start</label>
                <div class="control">
                    <div class="select">
                        <select id="startTime" value="@Model.savedEvent.StartTime" asp-for="myEvent.StartTime" asp-items="Model.ListOfStartTimeIntervals" class="form-control"></select>
                    </div>
                </div>
            </div>

            <div class="control">
                <label class="label">@Model.LangData.events.create.End</label>
                <div class="control">
                    <div class="select">
                        <select id="endTime" value="@Model.savedEvent.EndTime" asp-for="myEvent.EndTime" asp-items="Model.ListOfEndTimeIntervals" class="form-control"></select>
                    </div>
                </div>
                <p class="help is-danger">@Model.timeErrMsg</p>
            </div>
        </div>


        <div class="field">
            <label class="label">@Model.LangData.events.create.Location</label>
            <div class="control">
                <input class="input form-input-50" value="@Model.savedEvent.Location" asp-for="myEvent.Location"></input>
                <br/>
                <a class="has-text-success" href="https://www.skype.com/en/free-conference-call/" target="_blank">@Model.LangData.events.create.MeetingLink</a>
            </div>
        </div>

        <input type="hidden" value="@Model.Eid"/>

        <div class="field">
            <div class="control">
                <button class="button is-warning is-light">@Model.LangData.events.create.Edit</button>
            </div>
        </div>

    </form>
</div>

Pages/Events/View.cshtml
@page "{eid}"
@model KampongTalk.Pages.Events.ViewModel
@{
}

@section Scripts {
    @if (Model.amOwner)
    {
        <script>
            $("#renderImage").on('click', () => {
                $("input[name=eventImage]").click()
            })

            $("input[name=eventImage]").on('change', () => {
                console.log("Changed")
                $("#editImageForm").submit()
            })
        </script>
    }
}
<link rel="stylesheet" href="~/css/event.css">

@if (Model.isOver)
{
    <div class="section">
        <article class="message is-danger">
            <div class="message-header">
                <p>@Model.LangData.events.detail.viewOnly</p>

            </div>
            <div class="message-body">
                @Model.LangData.events.detail.archive
            </div>
        </article>
    </div>

    <div class="section">
        <div class="columns is-vcentered">
            <div class="column is-8">
                <figure class="has-text-centered">
                    <img src="~/imgs/@Model.myEvent.Img"/>
                </figure>
            </div>

            <div class="column is-4">
                <div class="content">
                    <h1 class="title is-size-3">@Model.myEvent.Name</h1>
                    <p class="subtitle is-size-7">@Model.LangData.events.detail.Organized : <a href="/Profile?u=@Model.OwnerUser.Uid2">@Model.OwnerUser.Name</a></p>
                    <br/>

                    <p>@Model.LangData.events.detail.Date: @Model.eventDate</p>
                    <p>@Model.LangData.events.detail.Duration: @Model.myEvent.Duration Hours</p>
                    <p>@Model.LangData.events.detail.Time: @Model.myEvent.StartTime - @Model.myEvent.EndTime</p>
                    <p>@Model.LangData.events.detail.Location: <a target="_blank" href="@Model.myEvent.Location">@Model.myEvent.Location</a></p>
                    <p>@Model.myEvent.Description</p>
                </div>
            </div>
        </div>
    </div>
}

// If event is not archived (Not over yet)
else
{
    <div class="section">
        <div class="columns is-vcentered">
            @if (Model.amOwner)
            {
                <partial name="Partials/_EditableImg"/>
            }
            else
            {
                <div class="column is-8">
                    <figure class="has-text-centered">
                        <img src="~/imgs/Events/@Model.myEvent.Img"/>
                    </figure>
                </div>
            }


            <div class="column is-4">
                <div class="content">
                    <h1 class="title is-size-3">@Model.myEvent.Name</h1>
                    <p class="subtitle is-size-7">@Model.LangData.events.detail.Organized : <a href="/Profile?u=@Model.OwnerUser.Uid2">@Model.OwnerUser.Name</a></p>
                    <br/>

                    <p>@Model.LangData.events.detail.Date: @Model.eventDate</p>
                    <p>@Model.LangData.events.detail.Duration: @Model.myEvent.Duration Hours</p>
                    <p>@Model.LangData.events.detail.Time: @Model.myEvent.StartTime - @Model.myEvent.EndTime</p>
                    <p>@Model.LangData.events.detail.Location: <a target="_blank" href="@Model.myEvent.Location">@Model.myEvent.Location</a></p>
                    <p>@Model.myEvent.Description</p>
                </div>

                @if (Model.amOwner)
                {
                    <a href="/Events/Edit/@Model.myEvent.Eid" class="button is-warning">
                        <span class="icon">
                            <i class="fas fa-wrench"></i>
                        </span>
                        <span>@Model.LangData.events.detail.Edit</span>
                    </a>
                }
                else
                {
                    <form asp-page-handler="AddOrRemove">
                        @if (!Model.hasAdded)
                        {
                            <button class="button is-success">
                                <span class="icon">
                                    <i class="fas fa-plus"></i>
                                </span>
                                <span>@Model.LangData.events.detail.Attend</span>
                            </button>
                        }
                        else
                        {
                            <button class="button is-danger">
                                <span class="icon">
                                    <i class="fas fa-minus"></i>
                                </span>
                                <span>@Model.LangData.events.detail.Remove</span>
                            </button>
                        }
                        <input type="hidden" asp-for="@Model.Eid" value="@Model.Eid"/>
                    </form>
                }
            </div>
        </div>
    </div>

    <div class="section">
        <p class="title">@Model.LangData.events.detail.Recommended</p>
        <div class="columns is-multiline is-variable is-5" id="displayedListings">
            @foreach (var myEvent in Model.recommendedEvents)
            {
                <div class="column is-one-third">
                    <a class="listing-clickable" href='/Events/View/@myEvent.Eid'>
                        <div class="box listing-image" style='background-image: url("/imgs/Events/@myEvent.Img")'>
                            <div>
                                <p class="content has-text-white">
                                    @myEvent.Description
                                </p>
                            </div>
                        </div>
                        <h3 class="title">@myEvent.Name</h3>
                    </a>
                </div>
            }
        </div>
    </div>
}